import React from "react";
import MaxWidthWrapper from "../layouts/MaxWidthWrapper";

interface Props {
  title: string;
  description: string;
}

const About: React.FC<Props> = ({ title, description }) => {
  return (
    <MaxWidthWrapper>
      <div className="bg-white py-20 flex flex-col gap-14">
        <div className="flex md:flex-row flex-col gap-8 md:gap-0 justify-around ">
          <p className="font-semibold md:text-titleSummaryTitle leading-15 text-2xl text-center md:text-left text-green-dark flex-1">
            {title}
          </p>
          <div className="px-1 md:px-0 flex-1 text-textSecondary font-light">
            {description}
          </div>
        </div>
        <div className="flex flex-col md:flex-row gap-8 justify-center">
          <div className="w-90 md:w-105 h-52 bg-skyblue rounded-3xl flex flex-col gap-2 pt-10 pl-10">
            <p className="font-semibold text-12.5 leading-heroTitle text-green-dark">
              $100K+
            </p>
            <p className="font-medium text-xl text-textSecondary">
              Revenue Generated by clients
            </p>
          </div>
          <div className="w-90 md:w-105 h-52 bg-mellowYellow rounded-3xl flex flex-col gap-2 pt-10 pl-10">
            <p className="font-semibold text-12.5 leading-heroTitle text-green-dark">
              45+
            </p>
            <p className="font-medium text-xl text-textSecondary">
              Team of Tech Experts
            </p>
          </div>
          <div className="w-90 md:w-105 h-52 bg-purple rounded-3xl flex flex-col gap-2 pt-10 pl-10">
            <p className="font-semibold text-12.5 leading-heroTitle text-green-dark">
              150+
            </p>
            <p className="font-medium text-xl text-textSecondary">
              Project Delivered
            </p>
          </div>
        </div>
      </div>
    </MaxWidthWrapper>
  );
};

export default About;
