import React from "react";
import MaxWidthWrapper from "./MaxWidthWraper";

interface Props {
  mainLine: string,
  description: string
}

const About: React.FC<Props> = ({mainLine, description}) => {
  return (
    <MaxWidthWrapper>
    <div className="bg-white py-20 flex flex-col gap-14">
      <div className="flex md:flex-row flex-col gap-8 md:gap-0 justify-around ">
        <p className="font-semibold md:text-4xl text-2xl text-center md:text-left ">
          {mainLine}
        </p>
        <div className= "px-1 md:px-0">
          {description}
        </div>
      </div>
      <div className="flex flex-col md:flex-row gap-8 justify-center">
        <div className="w-90 md:w-105 h-52 bg-skyblue rounded-3xl flex flex-col gap-6 pt-10 pl-10">
          <p className="font-bold text-6xl">$100K+</p>
          <p className="font-semibold text-xl text-gray-700">
            Revenue Generated by clients
          </p>
        </div>
        <div className="w-90 md:w-105 h-52 bg-mellowYellow rounded-3xl flex flex-col gap-6 pt-10 pl-10">
          <p className="font-bold text-6xl">45+</p>
          <p className="font-semibold text-xl text-gray-700">
            Team of Tech Experts
          </p>
        </div>
        <div className="w-90 md:w-105 h-52 bg-purple rounded-3xl flex flex-col gap-6 pt-10 pl-10">
          <p className="font-bold text-6xl">150+</p>
          <p className="font-semibold text-xl text-gray-700">
            Project Delivered
          </p>
        </div>
      </div>
    </div>
    </MaxWidthWrapper>
  );
};

export default About;
