import React from "react";

const About: React.FC = () => {
  return (
    <div className="bg-white py-20 flex flex-col gap-14">
      <div className="flex justify-around">
        <p className="font-semibold text-5xl">
          Know More About
          <br />
          Propelius Technologies
        </p>
        <div className="flex flex-col gap-6">
          <p>
            At Propelius, we dive deeper into the world of tech and work on our
            approach
            <br /> on how we're reshaping the digital landscape. Our team of
            seasoned experts
            <br /> brings a wealth of experience across various industries,
            ensuring that we
            <br /> understand your unique challenges and opportunities.
          </p>
          <p>
            We believe in the power of technology to transform businesses, and
            our track
            <br /> record speaks for itself. From advanced mobile apps to robust
            SaaS solutions,
            <br /> we've helped countless organisations achieve their digital
            goals. Connect with
            <br /> us to explore more about our case studies, and learn about
            our innovative
            <br /> approach to tech development. Our holistic approach to
            digital
            <br /> transformation encompasses everything from initial strategy
            to ongoing
            <br /> support. We're committed to transparency, keeping you
            involved and
            <br /> informed throughout the development process.{" "}
          </p>
        </div>
      </div>
      <div className="flex gap-8 justify-center">
        <div className="w-105 h-52 bg-skyblue rounded-3xl flex flex-col gap-6 pt-10 pl-10">
          <p className="font-bold text-6xl">$100K+</p>
          <p className="font-semibold text-xl text-gray-700">
            Revenue Generated by clients
          </p>
        </div>
        <div className="w-105 h-52 bg-mellowYellow rounded-3xl flex flex-col gap-6 pt-10 pl-10">
          <p className="font-bold text-6xl">45+</p>
          <p className="font-semibold text-xl text-gray-700">
            Team of Tech Experts
          </p>
        </div>
        <div className="w-105 h-52 bg-purple rounded-3xl flex flex-col gap-6 pt-10 pl-10">
          <p className="font-bold text-6xl">150+</p>
          <p className="font-semibold text-xl text-gray-700">
            Project Delivered
          </p>
        </div>
      </div>
    </div>
  );
};

export default About;
